name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: .
        run: mvn clean install

      - name: Run tests
        working-directory: .
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Production
        run: |
          echo "Deployment logic goes here"
          # This could involve deploying to a cloud provider, Docker, etc.

notify:
  runs-on: ubuntu-latest
  steps:
    - name: Send Email Notification 
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: GitHub Actions - Build ${{ job.status }}
        body: |
          The build for the Spring Boot application has ${{ job.status }}.
        to: subramaniravi22@gmail.com
        from: github-actions@example.com

notify-slack:
  runs-on: ubuntu-latest
  steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
